### ISSUE TITLE
apiProducts list for dev apps

### ISSUE THREAD

**Issue by pisitch1** [apigee/apigee-config-maven-plugin#10]
apiProducts list exist under /credentials in response of GET https://api.enterprise.apigee.com/v1/organizations/{org_name}/apps

However, the apiProducts accepted by the plug-in is nested just right under developerid/

    "grant@enterprise.com": [
        {
            "apiProducts": [
                "weatherProduct"
            ],
            "callbackUrl": "http://weatherapp.com",
            "name": "grantoneapp",
            "scopes": []
        },
        {
            "apiProducts": [
                "weatherProduct"
            ],
            "callbackUrl": "http://weatherapp.com",
            "name": "granttwoapp",
            "scopes": []
        }
    ],

Any reason why we have to structure this differently? This makes it hard for us to just extract the current Dev Apps configs using management API and reconstruct them in the environment.

**Comment by msadasivam** [comment]
The plugin defers the validation of the payload to the management API. Please try your format with the plugin. I expect it to work fine without any changes as long as the management API is happy with it.

**Comment by pisitch1** [comment]
Thanks for the response @msadasivam. The problem is that if I use the output from Management API for DevApp as is, the app will not contain any product because maven is expecting the apiproducts at root

**Comment by pisitch1** [comment]
Update on this guys? Tried the migrate tool but it spit out the same format that the Maven plugin didn't support.

**Comment by msadasivam** [comment]
@pisitch1 we got some understanding of the issue and working out what needs to be done. Fortunately a pull request came through with most of the stuff we need. If you are interested please take a look at  https://github.com/apigee/apigee-config-maven-plugin/pull/8

**Comment by msadasivam** [comment]
@pisitch1 if you have any feedback on the pull request, please feel free to comment in the pull request thread directly.

**Comment by pisitch1** [comment]
Has this been merged for me to pull and retry?

**Comment by msadasivam** [comment]
The pull request does not meet security best practices and the author is unresponsive. Any support for reading and deploying persisted key/secret allows insecure persistence in SCM like git. This is not desirable. @ssvaidyanathan added a feature to export app keys and was released today. 

Support for multiple credentials in an app is still outstanding. I cannot get to this change right away, but would treat this as the first enhancement to be picked up.

**Comment by pisitch1** [comment]
Do we have the fix for this yet? Thanks!

**Comment by pisitch1** [comment]
Discussed with Sai. The Maven plugin accepts the structure for the CREATE API call. So we'll need to write some external transformation logic to convert the GET API call output to the structure that plugin needs.
