### ISSUE TITLE
Config API Product without a proxy

### ISSUE THREAD

**Issue by heyitsaakash** [apigee/apigee-config-maven-plugin#100]
Hi,

Is it necessary to always give proxy name while creating a api product from apiproducts.json. Can it not be empty or null

I get an exception -
Failed to execute goal com.apigee.edge.config:apigee-config-maven-plugin:1.4.3:apiproducts (create-config-apiproduct) on project ConfigOnly: null: MojoExecutionException ->

In apigee edge we can create product without proxy name. But, When i execute command i  get maven error -

mvn install -Ptest -Dusername=xx  -Dpassword=xxx  -Dorg=xxx-eval  -Dapigee.config.options=create -Ddird=config

thanks,
Aakash

**Comment by ssvaidyanathan** [comment]
@heyitsaakash - no its not necessary. I just removed the proxy name from apiProducts.json. Was able to create the product. Please try and close the issue if it works

For example
```
[
    {
        "name": "weatherProduct",
        "displayName": "weatherProduct",
        "description": "weatherProduct",
        "apiResources": [
            "/**",
            "/"
        ],
        "approvalType": "auto",
        "attributes": [
            {
                "name": "description",
                "value": "json Product"
            },
            {
                "name": "developer.quota.limit",
                "value": "10000"
            },
            {
                "name": "developer.quota.interval",
                "value": "1"
            },
            {
                "name": "developer.quota.timeunit",
                "value": "month"
            }
        ],
        "environments": [
            "test"
        ],
        "proxies": [
        ],
        "quota": "10000",
        "quotaInterval": "1",
        "quotaTimeUnit": "month",
        "scopes": []
    }
]
```

**Comment by ssvaidyanathan** [comment]
No updates hence closing
