### ISSUE TITLE
™ in API Product Descripting is not working

### ISSUE THREAD

**Issue by Kittiman** [apigee/apigee-config-maven-plugin#105]
Hi,

We are creating an API Product suing the maven plugin and the product we try to create contains the ™ symbol.
We get this error.

[ERROR] Failed to execute goal com.apigee.edge.config:apigee-config-maven-plugin:1.4.3:apiproducts (create-config-apiproduct) on project apiproduct-xyz: Apigee network call error 400 Bad Request
[ERROR] {
[ERROR]   "message" : "Invalid UTF-8 middle byte 0x5c\n at [Source: org.apache.cxf.transport.http.AbstractHTTPDestination$1@2dd80afc; line: 1, column: 318]",
[ERROR]   "contexts" : [ ]
[ERROR] }
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

This is the JSON structure being used.

`[
  {
    "name": "apiproduct-xyz",
    "apiResources": [
      "/*"
    ],
    "approvalType": "auto",
    "attributes": [
        {
            "name": "description",
            "value": "XYZ™ API"
        },
        {
          "name": "access",
          "value": "private"
        }
    ],
    "description": "XYZ™ API",
    "displayName": "XYZ™ API",
    "environments": [test],
    "proxies": [
        "api-xyz"
    ],
    "quota": "1000",
    "quotaInterval": "1",
    "quotaTimeUnit": "day",
    "scopes": [
    ]
  }
]
`

**Comment by ssvaidyanathan** [comment]
@Kittiman - I tried the same payload you shared and it works with the 1.4.3 version

![image](https://user-images.githubusercontent.com/16812354/101940069-c6213700-3b9a-11eb-93ac-56ceffdc1c1d.png)

```
Request prepared for the server
 **************************
POST  https://api.enterprise.apigee.com/v1/organizations/<REDACTED>/apiproducts
accept: [application/json]
accept-encoding: [gzip]
authorization: [Bearer [Not shown in log]
content-type: application/json
 [Request body]
{"quotaInterval":"1","environments":["test"],"displayName":"XYZ™ API","apiResources":["\/*"],"approvalType":"auto","quota":"1000","quotaTimeUnit":"day","name":"apiproduct-xyz","description":"XYZ™ API","attributes":[{"name":"description","value":"XYZ™ API"},{"name":"access","value":"private"}],"proxies":["catalog"],"scopes":[]}
[INFO] Response application/json
{
  "apiResources" : [ "/*" ],
  "approvalType" : "auto",
  "attributes" : [ {
    "name" : "description",
    "value" : "XYZâ¢ API"
  }, {
    "name" : "access",
    "value" : "private"
  } ],
  "createdAt" : 1607710791211,
  "createdBy" : "<REDACTED>",
  "description" : "XYZâ¢ API",
  "displayName" : "XYZâ¢ API",
  "environments" : [ "test" ],
  "lastModifiedAt" : 1607710791211,
  "lastModifiedBy" : "<REDACTED>",
  "name" : "apiproduct-xyz",
  "proxies" : [ "catalog" ],
  "quota" : "1000",
  "quotaInterval" : "1",
  "quotaTimeUnit" : "day",
  "scopes" : [ ]
}
[INFO] Create Success.
```

**Comment by Kittiman** [comment]
This might be something encoding related because I have kind of same problem with the spec store and I can see that the character is not correctly represented as two bytes/characters as in your case. 
We get �
and you get �¢

Our build agent is a Windows server.
i have tried to make use of encoding but no luck there, yet!

This is the trace
```
Request prepared for the server 
 **************************
PUT  https://apigee.com/organizations/xxxxx-development/specs/doc/xxxxxxx/content
accept: [application/json]
accept-encoding: [gzip]
authorization: [Bearer [Not shown in log]
[INFO] Response application/json
openapi: 3.0.3
info:
  title: XYZAPI (Alpha)
  version: "1.0"
  description: "#XYZ� API  \nThe XYZ� 
```

**Comment by ssvaidyanathan** [comment]
@Kittiman - getting back to this issue
You opened the issue about API Product but your comment is for the Specs. Can you confirm if the issue still exist?

**Comment by ssvaidyanathan** [comment]
Closing this issue. Pls re-open if needed with additional info
