### ISSUE TITLE
Option to add delay in Apigee deployment

### ISSUE THREAD

**Issue by indrajitp** [apigee/apigee-config-maven-plugin#108]
Hello,

This is request to add override-delay option!
Calls are failing at the time of deployment when old revision gets undeployed and new one deploys.
As of now with this plugin you cannot deploy one revision of an API proxy on top of another. Deployment sequence should be like --> the new revision is deployed, and once the deployment is complete, the already deployed revision is undeployed. 

There is option of Seamless deployment using Apigee management API. 
https://docs.apigee.com/api-platform/deploy/deploy-api-proxies-using-management-api#seamless

Can we please add this override-delay option into this plugin as part of shared pom.xml?
This will ensure our calls do not fails since its a critical to lose any transaction.

Thanks,
Indrajit Patil

**Comment by ssvaidyanathan** [comment]
@indrajitp - you have the issue opened in the wrong GitHub project. For any Apigee Maven deploy plugin related issues, please open an issue [here](https://github.com/apigee/apigee-deploy-maven-plugin/issues/new)

Quick note - override option already exists. Please see the [README](https://github.com/apigee/apigee-deploy-maven-plugin) and also the [samples](https://github.com/apigee/apigee-deploy-maven-plugin/blob/e69739ffad36e1126942b922f197493381c6750a/samples/mockapi-recommended/src/gateway/shared-pom.xml#L110). Override is the default option. So if you want it to be override, you can ignore the `<apigee.options>` in the pom profile.

Am closing this issue as its not config plugin related. Please see the plugin [README](https://github.com/apigee/apigee-deploy-maven-plugin) and if you are still not getting it to work, please open [issue](https://github.com/apigee/apigee-deploy-maven-plugin/issues/new)
