### ISSUE TITLE
Example shared pom doesn't have goals related to Virtual Hosts deployment

### ISSUE THREAD

**Issue by dineshpalanivel** [apigee/apigee-config-maven-plugin#109]
The example **shared-pom.xml** does not have any goals for virtualhosts deployment. There is a sample json file (virtualHosts.json) in the sample directory (which is good). 

It would be great if we can update the shared-pom.xml to reflect the goals that we need to deploy Virtual Hosts. 

@ssvaidyanathan

**Comment by ssvaidyanathan** [comment]
@dineshpalanivel - That is on purpose. 
Virutal host config is something that does not change very often but if you change can cause downtime to your APIs. 
You dont want to include that to your POM file and then have it called by mistake

I would recommend you to have the configurations in the json file but call the Maven goal directly when you want to configure it something like

```mvn apigee-config:virtualhosts -Ptest -Dapigee.config.options=create -Dapigee.config.dir=./resources/edge```

**Comment by dineshpalanivel** [comment]
> @dineshpalanivel - That is on purpose.
> Virutal host config is something that does not change very often but if you change can cause downtime to your APIs.
> You dont want to include that to your POM file and then have it called by mistake
> 
> I would recommend you to have the configurations in the json file but call the Maven goal directly when you want to configure it something like
> 
> `mvn apigee-config:virtualhosts -Ptest -Dapigee.config.options=create -Dapigee.config.dir=./resources/edge`
> 
> If you really want to include it to your pom file, please add the below lines to your pom file
> 
> ```
> <execution>
>     <id>create-config-virtualhost</id>
>     <phase>install</phase>                        
>     <goals>
>         <goal>virtualhosts</goal>
>     </goals>
> </execution>
> ```

Makes perfect sense @ssvaidyanathan . We have created a separate pipeline just to manage the virtual hosts and the example that you have provided was helpful. We looked at the java code and figured out what the maven goal should be. :) 

Worst case, if you think that the community would benefit with an updated README with a section specific to deploying virtual hosts, pls consider. 

Thanks again.

**Comment by ssvaidyanathan** [comment]
There isnt anything specific about Virtual host. Need to make sure that the payload is correct with all the properties. Like any other Management API, Virtual host expects certain parameters and if they are provided, the plugin picks that up and pushes that to Apigee. 

There is a section in the README that lists the various goals available in the plugin and you can use any one directly and call within your pipeline

I am closing this issue for now
