### ISSUE TITLE
Not able to do seamless deployment

### ISSUE THREAD

**Issue by sanjeevks1** [apigee/apigee-config-maven-plugin#110]
is there any way to implement seamless deployment. We tried using override delay parameter but still not able to achieve the same. Can some one please let me know if they have implemented the same using apigee-config-maven-plugin.

**Comment by ssvaidyanathan** [comment]
@sanjeevks1 - you have the issue opened in the wrong GitHub project. For any Apigee Maven deploy plugin related issues, please open an issue [here](https://github.com/apigee/apigee-deploy-maven-plugin/issues/new)

Quick note - override option already exists. Please see the [README](https://github.com/apigee/apigee-deploy-maven-plugin) and also the [samples](https://github.com/apigee/apigee-deploy-maven-plugin/blob/e69739ffad36e1126942b922f197493381c6750a/samples/mockapi-recommended/src/gateway/shared-pom.xml#L110). Override is the default option. So if you want it to be override, you can ignore the `<apigee.options>` in the pom profile.

Am closing this issue as its not config plugin related. Please see the plugin [README](https://github.com/apigee/apigee-deploy-maven-plugin) and if you are still not getting it to work, please open [issue](https://github.com/apigee/apigee-deploy-maven-plugin/issues/new)
