### ISSUE TITLE
aliases [1.x.x - 2.x.x Feature Parity]

### ISSUE THREAD

**Issue by danistrebel** [apigee/apigee-config-maven-plugin#113]
It would be great to have the option to also create `aliases` for Apigee X and hybrid.

The example currently assumes that the alias was generated externally:

https://github.com/apigee/apigee-config-maven-plugin/blob/master/samples/EdgeConfig/edge.json#L16

**Comment by ssvaidyanathan** [comment]
Fixed in v2.1.1
