### ISSUE TITLE
Developer apps - update option creates new credentials on each deployment (v2.x.x)

### ISSUE THREAD

**Issue by dfsabugal** [apigee/apigee-config-maven-plugin#128]
This is the same issue described in https://github.com/apigee/apigee-config-maven-plugin/issues/17, but the fix is not available for Apigee X/Hybrid, i.e., not available in versions 2.x.x.

**Comment by ssvaidyanathan** [comment]
Released in v2.1.2

**Comment by dfsabugal** [comment]
> Released in v2.1.2

Thank you @ssvaidyanathan!
