### ISSUE TITLE
Update option replicate the same Products in an App

### ISSUE THREAD

**Issue by matias2681** [apigee/apigee-config-maven-plugin#14]
I was using the org edge configuration from [here](https://github.com/apigee/apigee-config-maven-plugin/tree/master/samples/EdgeConfig/resources/edge/org) and run it with the update option `-Dapigee.config.options=update` . 

My expectations were that updates the application but keeps the same `Consumer Key` and `Consumer Secret`. However,  it's adding every time the same product to the application with a different set of keys.

![image](https://cloud.githubusercontent.com/assets/5032554/26180104/3e776cac-3b1c-11e7-9caf-bb84c960a3a1.png)

That seems to be a bug.

Is there a way to reuse the same set of keys when we are using the `update` option?

Also, maybe as a feature request. It would be nice to use the same JSON format to define applications and products like the response from the [apps API](http://docs.apigee.com/management/apis/get/organizations/%7Borg_name%7D/developers/%7Bdeveloper_email_or_id%7D/apps) and [products API](http://docs.apigee.com/management/apis/get/organizations/%7Borg_name%7D/apiproducts/%7Bapiproduct_name%7D).

**Comment by msadasivam** [comment]
@matias2681 
To continue using existing keys please use apigee.config.options=create
mvn apigee-config:apps -Ptest -Dapigee.config.options=create
apps and developers belong to API publish phase and need not be part of each deployment. 

Alternatively, to use newly created app key/secret in tests please use the "apigee.config.exportDir" option to export newly created key/secret.

Replaying an old key/secret has the risk of users tracking them in git. The above 2 options would take care of CI usecases.

On your last point, yes, the plugin uses the POST/PUT payload of management APIs. The response payload of these APIs includes additional attributes and cannot be directly used at the moment.

**Comment by JasonNorth** [comment]
@msadasivam 

I think I have the same problem as described here.  In terms of using:
mvn apigee-config:apps -Ptest -Dapigee.config.options=create

If the app already exists it is skipped therefore any differences between the config and what is in Apigee to the app will not get applied.  What we ideally need is a way of specifying the required state of an App in config and then using apigee-config-maven-plugin to apply that state.  Is that possible with apigee-config-maven-plugin please?

**Comment by dotNetkow** [comment]
Ran into this issue today, seems we're not the only ones.  FWIW, if the plugin doesn't end up being updated but you'd like to accomplish this separately, use the [Add API Product to Key](https://apidocs.apigee.com/management/apis/post/organizations/%7Borg_name%7D/developers/%7Bdeveloper_email_or_id%7D/apps/%7Bapp_name%7D/keys/%7Bconsumer_key%7D) org management endpoint.

**Comment by ssvaidyanathan** [comment]
To accomplish that - you will first need to delete the app and then create the app in your pipeline using the delete and create option for the apps alone or use sync option specifically for the apps 

Going back to what @dotNetkow mentioned, if we use the [Add API Product to Key](https://apidocs.apigee.com/management/apis/post/organizations/%7Borg_name%7D/developers/%7Bdeveloper_email_or_id%7D/apps/%7Bapp_name%7D/keys/%7Bconsumer_key%7D)  then you will need to have the client Id in your repository which is not recommended

**Comment by ssvaidyanathan** [comment]
Fixed in v1.4.5 - [README](https://github.com/apigee/apigee-config-maven-plugin#update-developer-app-and-company-app-from-v145-onwards) section for this
