### ISSUE TITLE
Plugin used for handling config params.

### ISSUE THREAD

**Issue by anoopsaxena** [apigee/apigee-config-maven-plugin#148]
We need to manage Apigee config like cache, kvm, target servers, but as per the documentation of  Apigee-config plugin used for experimental purpose only.. kindly refer the below lines from readme section..
 
_NOTE The mvn apigee-config:specs - uses API whose contract and designs are experimental and expected to change, so may > break at any time and without warning. There are no guarantees of reliability, performance, stability, or support -- use at > your own risk_

hence  confused to use this plugin, Can we use this plugin for managing config params to our organization, Kindly suggest.
 
Thanks you.

**Comment by ssvaidyanathan** [comment]
@anoopsaxena - the experimental purpose only was for the Specs API because the Management API powering the Specs are not GA yet. For your requirements, you can use the plugin directly. Refer to the repo's samples and try it out.

Please reopen this issue if you still have any issues.
