### ISSUE TITLE
Creating KVM entries in Apigee Hybrid

### ISSUE THREAD

**Issue by cosmin-ciuc** [apigee/apigee-config-maven-plugin#156]
Hello,

Is it possible to create entries in an environment KVM from Apigee Hybrid? I'm using plugin version 2.3.0 but I've been unable to populate the KVMs I've created with entries.

A minimal sample file would be very useful.

Thank you.

**Comment by ssvaidyanathan** [comment]
Thanks for creating this issue @cosmin-ciuc 
The plugin does not have that feature in the 2.x version as the Apigee Management API supporting the KVM entries just got released. Will work on the feature and update once its released.

**Comment by ssvaidyanathan** [comment]
Fixed and released in v2.4.0

**Comment by xjjh1** [comment]
@ssvaidyanathan 

Greetings, I would like to know if this has been fixed in 2.4.0 as mentioned. I am using the same 2.4.0 latest, but however, I am unable to put encrypted entries on kvm using this plugin. 

```
<groupId>com.apigee.edge.config</groupId>
<artifactId>apigee-config-maven-plugin</artifactId>
<version>2.4.0</version>
```

Below is the error. Also, I have seen the community posts [https://www.googlecloudcommunity.com/gc/Apigee/APIGEE-Hybrid-Encryption-error-while-creating-Key-Value-Map/m-p/439873#M71210](url) and [https://www.googlecloudcommunity.com/gc/Apigee/Apigee-X-API-and-KVM/m-p/431291#M70915](url), that states still it will not work on Hybrid and may get fixed on 1.8. 

Can you please check and advise? 
```

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.562 s
[INFO] Finished at: 2022-08-12T13:04:26+10:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.apigee.edge.config:apigee-config-maven-plugin:2.4.0:kvms (default-cli) on project ENT_ICC_Apigee_HealthProbe: Apigee network call error 500 Internal Server Error
[ERROR] {
[ERROR]   "error": {
[ERROR]     "code": 500,
[ERROR]     "message": "Error while encrypting for encrypted KeyValueMap KeyValueMapScope {ScopeType ='ENVIRONMENTS', Organization = 'ieg-prod-be02', Environment = 'prod'}",
[ERROR]     "status": "INTERNAL",
[ERROR]     "details": [
[ERROR]       {
[ERROR]         "@type": "type.googleapis.com/google.rpc.PreconditionFailure",
[ERROR]         "violations": [
[ERROR]           {
[ERROR]             "type": "keyvaluemap.service.ErrorDuringEncryption",
[ERROR]             "subject": "[2002:a17:90a:cf8c::]:4338:sfbrm14:9896:879909:6242653",
[ERROR]             "description": "Error while encrypting for encrypted KeyValueMap KeyValueMapScope {ScopeType ='ENVIRONMENTS', Organization = 'ieg-prod-be02', Environment = 'prod'}"
[ERROR]           }
[ERROR]         ]
[ERROR]       },
[ERROR]       {
[ERROR]         "@type": "type.googleapis.com/google.rpc.RequestInfo",
[ERROR]         "requestId": "13405522103294437347"
[ERROR]       }
[ERROR]     ]
```

**Comment by ssvaidyanathan** [comment]
@xjjh1 - this should work with this version
For the KVM entries to work, Apigee runtime instance should be on 1.8

**Comment by xjjh1** [comment]
@ssvaidyanathan Thanks! 

I will wait for 1.8 to be released.
