### ISSUE TITLE
Unable to add product to the existing app

### ISSUE THREAD

**Issue by Raja09** [apigee/apigee-config-maven-plugin#159]
Hi  @ssvaidyanathan,

I am unable to add the product to my existing app for existing keys, as per [API Key: Developer DOC](https://apidocs.apigee.com/docs/developer-app-keys/1/routes/organizations/%7Borg_name%7D/developers/%7Bdeveloper_email%7D/apps/%7Bapp_name%7D/keys/%7Bconsumer_key%7D/put), instead of adding the product to the existing keys it creates new credentials. Due to this issue unable to access API with existing APP Credentials.

Kindly advise me on the same how can I resolve this issue and find the screenshots for the same

<img width="1585" alt="developer-app-notes" src="https://user-images.githubusercontent.com/7008185/187900518-cd290205-c984-44ee-b61c-f7fb0f6f3e15.png">
<img width="484" alt="developerApps-config" src="https://user-images.githubusercontent.com/7008185/187900525-ee707848-7a77-487f-b0f4-8e1b97cb4b16.png">
<img width="879" alt="devloper-app" src="https://user-images.githubusercontent.com/7008185/187900527-fe2ed716-5f06-42e7-afa5-12dd33069f35.png">

Thanks & Regads,
Raja sekhar

**Comment by ssvaidyanathan** [comment]
@Raja09 - which version of the plugin are you using? What is the mvn command you are executing?

**Comment by Raja09** [comment]
Hi @ssvaidyanathan,

Thanks for responding to my query, Please find the requested details below:

1. MVN command is used to update or create and existing APP: mvn install -Ptest -Dusername=xxxxxx -Dpassword=xxxxxx -Dapigee.config.file=resources/edge/org/developerApps.json -D apigee.config.options=update
2. Taken the checkout from master banch of the repository. Please confirm should I take checkout from release tag v2.4.0


Thanks & Regards, 
Raja Sekhar

**Comment by ssvaidyanathan** [comment]
@Raja09 - you do not need to checkout from master branch or tag. The plugins are already published to the Central Maven repo. So you pom can just point to that and fetch it. Like the ones available in the samples folder.

Need one more question's answer - Are you trying to push to Apigee Edge or Apigee X?

**Comment by Raja09** [comment]
@ssvaidyanathan,

I am trying to push the code into APIGEE Edge SaaS.

Please find the POM xml to identify the issue.

Thanks & Regards,
Raja Sekhar

**Comment by ssvaidyanathan** [comment]
@Raja09 - you do not need to use the pom file of the actual plugin. Please refer to the samples directory. That is similar to your project. You do not need the root-pom.xml. You only need the EdgeConfig-pom.xml

**Comment by ssvaidyanathan** [comment]
@Raja09 - how often do you need this? From what I see, adding a product to an existing credential within an app is not something thats done that often. 
This feature is not supported in the plugin. The plugin does not support credential management as we did not want customers to include consumerKey and secret in their git repo. Its not recommended. 
For your use case, you will need to use the API directly or use the UI

**Comment by Raja09** [comment]
@ssvaidyanathan,
Very often we add our product to an existing credentilas within an app and currently we using UI to updated our product into the existing credentials of an APP.

Thanks & Regards,
Raja Sekhar

**Comment by ssvaidyanathan** [comment]
Unfortunately the plugin does not support and will not be added either. Please use the API
Closing this issue
