### ISSUE TITLE
Difference in Update operation for KVMs between Apigee Edge and Apigee X/Hybrid

### ISSUE THREAD

**Issue by cchoung** [apigee/apigee-config-maven-plugin#162]
Hello, 

I noticed that the update config option works differently for KVMs in for apigee X/Hybrid than it does for Edge.

The Edge version works as a proper update, adding a new key-value pair to an existing KVM. The X version though essentially overwrites the KVM with whatever is in the kvms.json file.

I wanted to ask why this is and request if it could be changed so that they work the same.

For Edge (master branch), it simply updates the KVM, this can be seen in https://github.com/apigee/apigee-config-maven-plugin/blob/master/src/main/java/com/apigee/edge/config/mavenplugin/KVMMojo.java

lines 202-208

```
....
 if (existingKVM.contains(kvmName)) {
    switch (buildOption) {
        case update:
            logger.info("Env KVM \"" + kvmName + 
                                    "\" exists. Updating.");
            kvmEnv.update(new KvmValueObject(serverProfile, kvmName, kvm));
            break;
...
```

But for X/Hybrid (hybrid branch), it deletes the KVM, re-creates it, and then updates it. This can be seen in https://github.com/apigee/apigee-config-maven-plugin/blob/hybrid/src/main/java/com/apigee/edge/config/mavenplugin/KVMMojo.java

lines 207-233

```
 if (existingKVM.contains(kvmName)) {
    ...
        case update:
            logger.info("Env KVM \"" + kvmName + 
                                    "\" exists. Updating.");
            //deleting the KVM and re-creating the KVM and entries
            deleteEnvKVM(serverProfile, kvmName);
            createEnvKVM(serverProfile, kvmName);
            kvmEnv.update(new KvmValueObject(serverProfile, kvmName, kvm));
            break;
        case sync:
            logger.info("Env KVM \"" + kvmName + 
                "\" already exists. Deleting and recreating.");
            deleteEnvKVM(serverProfile, kvmName);
            logger.info("Creating Env KVM - " + kvmName);
            createEnvKVM(serverProfile, kvmName);
            kvmEnv.update(new KvmValueObject(serverProfile, kvmName, kvm));
            break;
...
```

I also noticed that the update and sync operations in the hybrid branch are doing the same thing, so I'm wondering if this was a mistake?

**Comment by ssvaidyanathan** [comment]
@cchoung - This is because Apigee X and hybrid does not support an update to a KVM entry via Management API. So the plugin is basically do a delete and create (with the latest you have in the json file). 

Since the update is creating and deleting, its what sync is as well.. so you see both doing the same thing

**Comment by cchoung** [comment]
I see. So if one wants to add new entries or update existing ones to an existing KVM, then you would have to grab the KVM through the API and do the additions/updates yourself?

**Comment by ssvaidyanathan** [comment]
@cchoung - Not really. What ever you want to update, do them on the kvms.json file and run the `sync` or `update` command. It will push whatever you have in the json file (as a whole)

**Comment by cchoung** [comment]
Yes, but if I'm understanding this correctly then that only works with the assumption that the kvms.json file is already up to date with its corresponding KVMs.
I will not be in a situation where that assumption is always true.

**Comment by ssvaidyanathan** [comment]
I would recommend your source of truth be in your source code repo and if you want to update any entry, just update the kvm.json and have the pipeline push it. In X, today, you dont have an option in the UI to create entries anyways.

**Comment by cchoung** [comment]
Thanks for the insight and the quick responses! Closing this out.
