### ISSUE TITLE
kvms is skipped in APIandConfig deployment

### ISSUE THREAD

**Issue by prashantsc2211** [apigee/apigee-config-maven-plugin#164]
Executing below command and in all orgConfig's got created but kvms are not getting created
mvn install -Dapigee.config.options=update -Pdev -Dusername=xxxx -Dpassword=xxxx
To create a KVM i have to manually add apigee-config:kvms in the command.

**Comment by prashantsc2211** [comment]
Hi, 
Yes this isn’t available , where would i find this details related to goals? In case i ll face issue for any other configuration.

**Comment by ssvaidyanathan** [comment]
Please check the README, the goals are all listed

**Comment by prashantsc2211** [comment]
Thanks
