### ISSUE TITLE
What is the most latest version that supports APIGEE Edge?

### ISSUE THREAD

**Issue by mrzjordan16** [apigee/apigee-config-maven-plugin#166]
What latest version of the apigee-config-maven-plugin is compatible with Apigee Edge? Is it possible that the most recent version will also support Apigee Edge?

We have an APIGEE Edge on-prem infrastructure and want to deploy KVM on it with "Multi-file config" option 

I'd like to know which  apigee-config-maven-plugin Latest Release version supports APIgee Edge.

**Comment by ssvaidyanathan** [comment]
@mrzjordan16 - Please check this [section](https://github.com/apigee/apigee-config-maven-plugin#note) of the README that talks about the version you could use for Apigee Edge and Apigee X/hybrid. You can find the latest versions [here](https://github.com/apigee/apigee-config-maven-plugin/releases). As of today, the latest version that support Edge is v1.5.3
