### ISSUE TITLE
Revert the changes - Undeploy

### ISSUE THREAD

**Issue by Navneet-10** [apigee/apigee-config-maven-plugin#169]
Is there any possible where proxy can undeployed by that I mean all the changes made by this plugin to the Apigee X should be reverted back or the resources created should be deleted.

**Comment by ssvaidyanathan** [comment]
@Navneet-10 - there are "delete" options available on both plugins. If you see something is wrong, you can just run the pipeline with the "delete" option.

**Comment by Navneet-10** [comment]
Thankyou

**Comment by ssvaidyanathan** [comment]
Can we close this issue?
