### ISSUE TITLE
When is the new version on 1.x going to be released ?

### ISSUE THREAD

**Issue by nikhilchawla123** [apigee/apigee-config-maven-plugin#172]
Currently, the Latest version of the Apigee Edge plugin is 1.5.3. But this version is using Springboot 5.3.18 dependency. And this Springboot version is obsolete as per Tidelift security compliance. Versions that are approved are either 5.3.26 or 6.x

**Comment by ssvaidyanathan** [comment]
@nikhilchawla123 - it does not use springboot in particular. There are other Spring dependencies like core, context and web.

**Comment by ssvaidyanathan** [comment]
will `5.3.27` work?

**Comment by ssvaidyanathan** [comment]
just released v1.5.4 with the Spring 5.3.27
