### ISSUE TITLE
apigee-config-maven-plugin:2.4.4:keyvaluemaps option UPDATE delete entries that doesnt exist in the kvms.json file

### ISSUE THREAD

**Issue by eceledonio2296** [apigee/apigee-config-maven-plugin#174]
Im trying to use the option: **apigee-config:keyvaluemaps** with the **apigee-config-maven-plugin:2.4.4**, but when I execute my maven command(mvn process-resources apigee-config:keyvaluemaps -Dapigee.config.options=update -Dapigee.bearer=$APIGEE_TOKEN) all the entries that are not specified in the kvms.json file are deleted and then the plugin create the new entries.

For example I have the next entry in my kvm:
```
{
    "keyValueEntries": [
        {
            "name": "ausername-novo2",
            "value": "EXMPL"
        }
    ],
    "nextPageToken": ""
}
```
then since I have the next entries in my kvms.json file:
```
[
    {
        "entry": [
            {
                "name": "ausername-novo3",
                "value": "EXMPL4"
            },
            {
                "name": "ausername-novo4",
                "value": "EXMPL4"
            }
        ],
        "name": "credenciales"
    }
]
```
I'm expecting that the result is the next:
```
{
    "keyValueEntries": [
        {
            "name": "ausername-novo2",
            "value": "EXMPL"
        },
       {
                "name": "ausername-novo3",
                "value": "EXMPL4"
        },
        {
                "name": "ausername-novo4",
                "value": "EXMPL4"
        }
    ],
    "nextPageToken": ""
}
```
But the command delete the key value map and then create only the last entries:
![kvms](https://user-images.githubusercontent.com/81441363/236967514-c5f0972c-9e3f-4147-8b90-98240da68298.png)

```
{
    "keyValueEntries": [
        {
            "name": "ausername-novo3",
            "value": "EXMPL4"
        },
        {
            "name": "ausername-novo4",
            "value": "EXMPL4"
        }
    ],
    "nextPageToken": ""
}
```
my maven command is the next: 
`mvn process-resources apigee-config:keyvaluemaps -Dapigee.config.options=update -Dapigee.bearer=$APIGEE_TOKEN`

**Comment by ssvaidyanathan** [comment]
@eceledonio2296 - yes this is working as expected as there are not APIs to update the KVMs. So the plugin deletes the entries and creates them from the json file you pass. If you want to add more entries, you will need to add them to existing JSON file so that it updates all the entries per your json

**Comment by eceledonio2296** [comment]
I understand but exist a reason for don't use the endpoint **add entry** [instead?:](https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations.environments.keyvaluemaps.entries/create) 
`curl --location 'https://apigee.googleapis.com/v1/organizations/{{org}}/environments/{{env}}/keyvaluemaps/{{keyvaluemapname}}/entries' \
--header 'Authorization: Bearer ' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--data '{
    "name": "name",
    "value": "value"
}'`

**Comment by ssvaidyanathan** [comment]
Yes - the plugin uses that API to add the entries and its part of the main the KVM goal. 
You are specifically asking to manage an entry to an existing KVM which does not exist today.
