### ISSUE TITLE
Plugin logs developer app credentials in clear text

### ISSUE THREAD

**Issue by patrick-zinner** [apigee/apigee-config-maven-plugin#175]
If you use the plugin (for Apigee X) and use it to create developer apps, it logs the consumerKeys and consumerSecrets in clear text. There is no way to turn off this behaviour, even if you configure the log level to NONE.

**Comment by patrick-zinner** [comment]
Sounds reasonable!

**Comment by ssvaidyanathan** [comment]
I've fixed and released a new version v2.4.5
Please test using that and then re-open this issue if the issue still not fixed
