### ISSUE TITLE
Datamasking is not working

### ISSUE THREAD

**Issue by kumarimajji** [apigee/apigee-config-maven-plugin#178]
We want to do data masking via automation Jenkins jobs. I have added the data masking configuration in the edge.json file
{
   "version": "1.0",
   "orgConfig":{
      "maskconfigs":[
         {
            "variables":[
               "request.header.X-Forwarded-Proto"
            ]
         }
      ]
   }
}
--added maskconfg goal in shared pom .xml
<execution> 
                        <id>create-config-maskconfigs</id>
                        <phase>install</phase>
                        <goals>
                            <goal>maskconfigs</goal>
                        </goals>
                    </execution>
The jobs are running successfully but when I check the trace I could see value in the trace. The values are not masking.

**Comment by ssvaidyanathan** [comment]
@kumarimajji - can you confirm from the Jenkins job logs that the Maven goal for datamask is executing?
