### ISSUE TITLE
Adding business logic for updating Flow Hooks when empty string

### ISSUE THREAD

**Issue by AyushGupta1-2-3** [apigee/apigee-config-maven-plugin#180]
Hello, 

This is a request to update flow hooks when empty string is passed in flowhooks.json
Given sample :
```
[
	{
	    "flowHookPoint":"PreProxyFlowHook",
             "sharedFlow": ""    
	},    
	{
	     "flowHookPoint":"PostProxyFlowHook",
             "sharedFlow":  ""
	}
]
```

Currently, when run with maven update option, Apigee management api looks for shared flow name with empty string 
and fails. 

In order to update the flow hook with no shared flow, business logic can be added in update maven option to call detach flow hook apigee management api.

**Comment by ssvaidyanathan** [comment]
Pushed a logic for this

Try using v2.4.6

Pls reopen if the issue still exist
