### ISSUE TITLE
Unable to add product into app due to maven plugin argument

### ISSUE THREAD

**Issue by ss2347** [apigee/apigee-config-maven-plugin#185]
Hi Team,

For the app TEST_APP_POC, when we tried to set another api product (Aurora), it didn't get updated in apigee and only the already existing SOLR product was showing. It is due to the additional mvn argument -Dapigee.app.ignoreAPIProducts=true being passed in the run maven operation. When we set it as false, the new api product also got mapped to the app.
This mention flag is present in workflow: ConfigDeployGit.
kindly check the same and revert us.

Thanks,
Sayan

**Comment by ssvaidyanathan** [comment]
@ss2347 - not sure what the ask is? 
That flag is meant to just update the app details and not update the products as the argument name suggest. Check [this](https://github.com/apigee/apigee-config-maven-plugin#update-developer-app-and-company-app-from-v212-onwards) section of the README that provides more info on why that flag is used. 

Are you asking about that. Your issue has no details around which version you are using, what is the Maven command you are passing not have logs. Please clarify your question or issue elaborately.

**Comment by ss2347** [comment]
Hello,
While calling maven plugin and the operation called run maven during that time argument is passing " -Dapigee.app.ignoreAPIProducts=true"" which is blocking to add app into the existing product.
due to this argument its blocking to add app into product.
for more details kindly share your convenient time so i can set up call and also include the flexdeply team.

Thanks,
Sayan

**Comment by ssvaidyanathan** [comment]
@ss2347 - if you do not want to ignore the API Products while updating the App, then you need to exclude that argument. 
Please bear in mind that whenever you try to update an app with products in it, it will create new set of credentials. Thats why the argument was introduced. Please have yout flexdeply team explain what issue they are facing on the issue.

**Comment by ss2347** [comment]
Hi, 
yes i know if we remove this argument then new set of cred will be created. for this we raised this to maven community to have the solution for both the cases. 
1. No New set cred will be created to the app
2.  Product will be added to the app or app is included into existing product.

Flexdeply team revert us to check with maven community. kindly provide your convenient time so we can setup call tomorrow IST hours. 1pm IST to 8PM IST is our preferable time.

Thanks,
Sayan

**Comment by ssvaidyanathan** [comment]
Not sure what you mean by the "maven community"

Unfortunately no one is available during the IST hours. You can provide more info here. 

Are you ok to generate new credentials when you associate a new product to the existing app? If yes, then you can use the "sync" option to delete and create the app again with the new set of products. But this will create a new credential as well.

If you want to add/remove products from an existing app, then the only option is to do that via UI or the API. The plugin does not support it at the moment.

**Comment by ssvaidyanathan** [comment]
1.No New set cred will be created to the app --> _Yes, you cannot do that with the plugin today. You will need to use UI or API_
Product will be added to the app --> _You can do that as one set. You can create an app with the list of products using the plugin_
or 
app is included into existing product --> _You cannot do this. You can associate API Products to app not the otherway round_

**Comment by ss2347** [comment]
Hi Team,

i dont want new set cred creation for migrating and as now code structure no new code will be crating as mvn argument -Dapigee.app.ignoreAPIProducts=true .

Is there any way along with above condition can i include app into existing product? 

Thanks,
Sayan

**Comment by ssvaidyanathan** [comment]
@ss2347 - am confused now
Are you trying to just add API Products to an existing app in an Apigee org?
or
Are you trying to migrate a set of apps with API Products along with credentials from one org to another?

Can you please be very clear on what you are trying to do?

**Comment by ss2347** [comment]
Hi Team,
Yes we just want to ADD product into existing APP, but its not possible due to  mvn argument -Dapigee.app.ignoreAPIProducts=true  argument.

Is there any way along with above condition can i include APP into existing PRODUCT ?

thanks,
Sayan

**Comment by ssvaidyanathan** [comment]
Yes - not possible with the plugin. You need to use the API or UI for this
