### ISSUE TITLE
KVM update doesn't support CPS orgs

### ISSUE THREAD

**Issue by seymen** [apigee/apigee-config-maven-plugin#19]
http://docs.apigee.com/management/apis/post/organizations/%7Borg_name%7D/environments/%7Benv_name%7D/keyvaluemaps/%7Bmap_name%7D/entries/%7Bentry_name%7D

**Comment by jvalde** [comment]
@msadasivam thanks, when are you planning to publish these changes?

**Comment by msadasivam** [comment]
v1.2.1 released.
