### ISSUE TITLE
Guidance needed with SAML based Dev Portal Access and developer provisioning

### ISSUE THREAD

**Issue by rohit3d2003** [apigee/apigee-config-maven-plugin#195]
According to the config-maven-plugin documentation, Developers, Developer Apps, and Products can be managed via source code. I need guidance on the following points:

1. When creating a Developer, is an invite sent to their email for setting a password and accessing the developer portal?
2. If the same Developer configuration exists across multiple repositories, will it recreate (and resend invite) or recognize and skip existing users? I understand this behavior might be adjustable through Maven command line options. Please confirm.
3. With a SAML-based identity provider instead of the built-in system, what behavior should we anticipate?

**Comment by ssvaidyanathan** [comment]
@rohit3d2003 - pls find my response below

> * When creating a Developer, is an invite sent to their email for setting a password and accessing the developer portal?
```
No - The email and setting up all comes into picture only when the developer goes to the developer portal and registers. You can still create the developer using this plugin or using the Apigee console
```

> * If the same Developer configuration exists across multiple repositories, will it recreate (and resend invite) or recognize and skip existing users? I understand this behavior might be adjustable through Maven command line options. Please confirm.

```
Yes - as you mentioned it depends on the option you pass in the command, if you use the "create" option, it will skip if it already exists, if you use "update", it will update what you pass. 
```

> * With a SAML-based identity provider instead of the built-in system, what behavior should we anticipate?

```
Can you elaborate? Are you referring to the IDP for the developer to login to the developer portal or are you referring to Apigee login itself with a SAML provider?

If its the former, then no change to the maven usage, you just create the developer as is. If its the latter, then you need to login and generate the access token and pass that access token to the plugin. Or use a service account json file that has appropriate permissions and pass that to the plugin
```

**Comment by rohit3d2003** [comment]
Apologies for my limited knowledge, but if we provision developers using a Maven plugin, how can they sign in without credentials? Does this mean that developer registration or signup is a separate process from this?

**Comment by ssvaidyanathan** [comment]
> Apologies for my limited knowledge, but if we provision developers using a Maven plugin, how can they sign in without credentials? Does this mean that developer registration or signup is a separate process from this?

This is more like a back door entry if you want. Typically, you would want the developer to go through the registration process in the portal and then login. Once logged in, he/she should create an app by attaching products that are published. 

You would want to create a developer in the Apigee console directly, if you want to by-pass that step (for testing, for example)


> Also, I was referring to the IDP for the developer portal.

No change to the maven plugin here as its completely difference from the developer portal

**Comment by ssvaidyanathan** [comment]
Closing this issue
