### ISSUE TITLE
Hide Cosumer key and Consumer Secret in console

### ISSUE THREAD

**Issue by Farneet** [apigee/apigee-config-maven-plugin#198]
I am using apigee-maven-config plugin to create api products and api keys with the following command in a tekton pipeline

`mvn -q --settings /opt/maven/settings.xml install 
        -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn 
        -P $APIGEE_ENV 
        -DSERVICE=$SERVICE 
        -DSTAGE=$STAGE 
        -DTENANT=$TENANT 
        -Dusername=$APIGEE_USERNAME 
        -Dpassword=$APIGEE_PASSWORD 
        -Dhttps.nonProxyHosts=${nonProxyHosts} 
        -Dhttp.nonProxyHosts=${nonProxyHosts} 
        -Dapigee.config.options=update \
        -Dapigee.app.ignoreAPIProducts=true \`

The issue is I can see the consumer apikey and consumer sercret in the tekton console. We send these logs to S3 and tekton pipelines can be seen and accesed by anyone in the company.
Is there any work around that Consumer Key and Consumer Secret are hidden 
   
![apigee](https://github.com/apigee/apigee-config-maven-plugin/assets/32062110/64399262-1c0a-4449-8952-2f20a340c3a5)

**Comment by ssvaidyanathan** [comment]
@Farneet - Thanks for bringing this up
I have updated those to debug logs so that it doesnt show up by default. 
The fix is pushed in `v1.5.5`
Please update your pom file to point to v1.5.5 and try it out
Closing this issue. Pls reopen if you have problems
