### ISSUE TITLE
Splitting KVMS into multiple files - Apigee X/Hybrid

### ISSUE THREAD

**Issue by dpalanivel** [apigee/apigee-config-maven-plugin#201]
This is similar to Issue #150 where splitting kvm configs into multiple files is not being recognized by the plugin.
Only **kvms.json** is recognized and processed.

The structure of the folder/files:

<img width="304" alt="image" src="https://github.com/apigee/apigee-config-maven-plugin/assets/5170022/0904d5a3-e448-4440-888d-e4c0ae865f1e">

[kvm-deploy.log](https://github.com/apigee/apigee-config-maven-plugin/files/14979810/kvm-deploy.log)
Snippet of logs from CD pipeline is attached for further investigation.

Additional information:

- Version: 2.7.0
- Maven command: `mvn install -P${apigeeDeployEnvironment} -Dapigee.config.options=${apigeeConfigDeployOption} -Dapigee.config.dir=./ -Dorg=${apigeeOrg} -DauthType=${authType} -Dbearer=$(gcloud auth print-access-token)`

@ssvaidyanathan Could you please review and help getting the fix from `1.5.3 `cascaded to `2.x` release?
@kurtkanaskie @rsrikant1982 FYI please.

**Comment by dpalanivel** [comment]
@rsrikant1982 ☝️

**Comment by ssvaidyanathan** [comment]
Thanks.. Will look into this

**Comment by ssvaidyanathan** [comment]
Just released v2.8.0 with this feature. Should be available in the Public repo in a few hours
This should work not only for KVMs, but for other entities as well (as long as you have the right prefix needed)
Try it out and let me know. Will close the issue after that

**Comment by dpalanivel** [comment]
@ssvaidyanathan there is a null pointer exception when the plugin tries to read config files. Shared details via email which either Kurt or Ankur might have shared with you. Could you please take a look?

**Comment by ssvaidyanathan** [comment]
@dpalanivel - I just released a patch v2.8.1 with the NPE fix. Please try it out as soon as its available in the Public repo. Sorry that was missed. Was a border test case.

**Comment by dpalanivel** [comment]
@ssvaidyanathan  All set and 2.8.1 worked. I truly appreciate the quick help on this. Thanks again.
