### ISSUE TITLE
Feature request: ApiCategory with custom id

### ISSUE THREAD

**Issue by juulia-jyrha** [apigee/apigee-config-maven-plugin#206]
I am experiencing issues with the current implementation of apiCategories. In apiCategories.json, you can only specify the name of the API category. However, to use this category in an apiProduct inside the apiDocs document, you need to reference it by its ID using the categoryIds tag. As the Id however, is not included in the API category creation request, it is generated randomly, making it unusable.

Since the API category creation endpoint accepts four parameters: id, siteId, name, and updateTime, can you allow the ID to be specified in the creation request? This would ensure the categories are usable.

**Comment by ssvaidyanathan** [comment]
@juulia-jyrha - you dont have to provide the ID in the apiDocs json. You just put the category name like this [sample](https://github.com/apigee/apigee-config-maven-plugin/blob/main/samples/EdgeConfig/resources/edge/org/apiDocs.json). The plugin will make an API call to get the ID for that category and replace that when making the actual API call for Docs.

Please try it and let me know if it still doesnt work

**Comment by juulia-jyrha** [comment]
Hi! I tried this and indeed that works. I just hadn't found this possibility anywhere in the documentation. Thank you.

**Comment by ssvaidyanathan** [comment]
Thanks - Didn't want to confuse and make it more easier for the plugin users.
