### ISSUE TITLE
Apigee Network Call 502 Proxy error

### ISSUE THREAD

**Issue by ruirain16** [apigee/apigee-config-maven-plugin#209]
Hi,

We tried to deploy API proxies using the cicd pipeline but we are not able to deploy and got an Apigee Network to call error.  We are using the pipeline to deploy an API specs to the Apigee and we used the apigee maven plugin to perform it.

We used the command below to deploy the API specs to the Apigee

`mvn apigee-config:specs "-P${{ parameters.Env }}" "-Dorg=${{ parameters.Org }}" "-Dusername=${{ parameters.Username }}" "-Dbearer=$(accessToken)" "-Dapigee.config.dir=$(Pipeline.Workspace)/drop/resources/edge" "-Dapigee.config.options=update" -X`

We tried to access the GET endpoint via postman. It's failing on the first call but it was successful after the succeeding calls.

Please see the image below for the reference 

Pipeline Error
![image](https://github.com/user-attachments/assets/a3396a61-5d68-4a6a-8117-fafb87d33f7d)

Postman 1st call: 502 Status
![image](https://github.com/user-attachments/assets/14f793bc-4383-467e-b54d-3ebc6858f2c6)

Postman succeeding calls: 200 Status
![image](https://github.com/user-attachments/assets/3e379f91-6b5c-4183-8548-d7351ade1ab8)

**Comment by VeronicaVivi** [comment]
Hi,
we have been experiencing the same error on the CI/CD pipeline for a few days (plugin version 1.4.3).
Thanks in advance to anyone who can provider support.

**Comment by ssvaidyanathan** [comment]
The APIs are in Preview and as mentioned in the logs are subjected to break and change without notice.

Since this is happening in Postman as well, this is not a plugin issue. I will reach out to the Engg team and ask them about it but the lead time might not be immediate.

**Comment by ApigeeCorky** [comment]
We have identified the issue and it should rollout sometime after Aug 13.

**Comment by ruirain16** [comment]
@ApigeeCorky sorry for the late response. It was already fixed on our end as well after you implemented the fix. May we know what is the fix? if it's allowed to know before closing the issue. thank you
