### ISSUE TITLE
Developer with + in email fails on App creation

### ISSUE THREAD

**Issue by kurtkanaskie** [apigee/apigee-config-maven-plugin#24]
Looks like '+' gets turned into ' '

[INFO] --- apigee-config-maven-plugin:1.1.4:apps (create-config-app) @ eatery-v1 ---
[INFO] ************************************************************************
[INFO] Apigee App
[INFO] ************************************************************************
[INFO] Retrieving Apps of **kurtkanaskie+jenkins@google.com**
[INFO] Creating App - Jenkins
[INFO] Request 
POST  https://api.enterprise.apigee.com/v1/organizations/kurtkanaskietrainer-trial/developers/kurtkanaskie%20jenkins@google.com/apps
accept: application/json
accept-encoding: gzip
authorization: Basic [Not shown in log]
content-type: application/json
 [Request body]
{"name":"Jenkins","callbackUrl":"http:\/\/myjenkins.com\/callback","scopes":[],"apiProducts":[]}
[ERROR] Apigee call failed 404 Not Found
{
  "code" : "developer.service.DeveloperIdDoesNotExist",
  "message" : "DeveloperId **kurtkanaskie jenkins@google.com** does not exist in organization kurtkanaskietrainer-trial",
  "contexts" : [ ]
}
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

**Comment by ssvaidyanathan** [comment]
@kurtkanaskie - Can you please share your developer and devApp entries that you are trying to create

**Comment by kurtkanaskie** [comment]
Here's the excerpt:
"developers": [{
                "email": "kurtkanaskie+jenkins@google.com",
                "firstName": "Kurt Jenkins Developer",
                "lastName": "Kanaskie",
                "userName": "kurtjenkinskanaskie",
                "attributes": []
            },
            {
                "email": "joesmith@example.com",
                "firstName": "Joe",
                "lastName": "Smith",
                "userName": "joesmith",
                "attributes": []
            },
            {
                "email": "janedoe@examle.com",
                "firstName": "Jane",
                "lastName": "Doe",
                "userName": "janedoe",
                "attributes": []
            }
        ],
        "developerApps": {
            "kurtkanaskie+jenkins@google.com": [{
                "name": "Jenkins",
                "apiProducts": [],
                "callbackUrl": "http://myjenkins.com/callback",
                "scopes": []
            }],
            "joesmith@example.com": [{
                "name": "EateryFinder",
                "apiProducts": ["Eatery"],
                "callbackUrl": "http://eateryfinder.com/callback",
                "scopes": []
            }],
            "janedoe@examle.com": [{
                "name": "EateryTrucks",
                "apiProducts": ["Eatery"],
                "callbackUrl": "http://eaterytrucks.com/callback",
                "scopes": []
            }]

**Comment by ssvaidyanathan** [comment]
@kurtkanaskie - have fixed the changes for the same. Should be available once the PR is approved

**Comment by ssvaidyanathan** [comment]
This is fixed in https://github.com/apigee/apigee-config-maven-plugin/releases/tag/apigee-config-maven-plugin-1.2
