### ISSUE TITLE
KVM option=update fails if KVM exists

### ISSUE THREAD

**Issue by kurtkanaskie** [apigee/apigee-config-maven-plugin#25]
$ mvn apigee-config:kvms -Ptest -Dapigee.config.options=update
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building eatery-kurtkanaskiev1 -
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- apigee-config-maven-plugin:1.1.4:kvms (default-cli) @ eatery-v1 ---
[INFO] ************************************************************************
[INFO] Apigee KVM
[INFO] ************************************************************************
[INFO] No org scoped KVM config found.
[INFO] Env KVM "ErrorMessages" exists. Updating.
[INFO] Request 
PUT  https://api.enterprise.apigee.com/v1/organizations/kurtkanaskietrainer-trial/environments/test/keyvaluemaps/ErrorMessages
accept: application/json
accept-encoding: gzip
authorization: Basic [Not shown in log]
[ERROR] Apigee call failed 410 Gone
{
  "code" : "keyvaluemap.service.KeyValueMapUpdateOperationNotSupported",
  "message" : "Update of KeyValueMap is not supported; use addEntry/updateEntry api to add entries to a KeyValueMap",
  "contexts" : [ ]
}
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

**Comment by ssvaidyanathan** [comment]
This is a duplicate - https://github.com/apigee/apigee-config-maven-plugin/issues/19

**Comment by ssvaidyanathan** [comment]
This is fixed in https://github.com/apigee/apigee-config-maven-plugin/releases/tag/apigee-config-maven-plugin-1.2
