### ISSUE TITLE
 apigee-config-maven-plugin:1.1.3:caches (create-config-cache) @ HelloWorld --- [INFO]  [INFO] Apigee Cache [INFO]  [INFO] Skipping Caches (default action)

### ISSUE THREAD

**Issue by Gokulakrishnanp1** [apigee/apigee-config-maven-plugin#26]
I am running Apigee Maven config plugin using jenkins and i get Skipping Actions as default. I need help setting up action to be executed.

**Comment by ssvaidyanathan** [comment]
@Gokulakrishnanp1 - can you please provide your mvn command you are executing in Jenkins ?
Can you confirm you are passing -Dapigee.config.options=create|update|delete|sync ?
If not, the default is none which means it will skip all config

**Comment by ssvaidyanathan** [comment]
@Gokulakrishnanp1 - can you provide the command ?
