### ISSUE TITLE
Build fails when using apigee.config.dir when no "api" directory exists

### ISSUE THREAD

**Issue by kurtkanaskie** [apigee/apigee-config-maven-plugin#30]
Fails on kvms phase even tho there are none. Given this simple config:
[kurtkanaskie:~/config-v1]$ tree edge
edge
└── org
.      ├── apiProducts.json
.      ├── developerApps.json
.     └── developers.json

and this command:
mvn -Pstage install -Dapigee.config.options=update -Dapigee.config.dir=edge

[INFO] --- apigee-config-maven-plugin:1.2:keyvaluemaps (create-config-kvm) @ config-v1 ---
[INFO] ************************************************************************
[INFO] Apigee KVM
[INFO] ************************************************************************
[INFO] Config file org/kvms.json not found.
[INFO] No org scoped KVM config found.
[INFO] Config file env/stage/kvms.json not found.
[INFO] No env scoped KVM config found.
**[INFO] Retrieving API list from edge/api**
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.684 s
[INFO] Finished at: 2017-10-26T13:39:32-04:00
[INFO] Final Memory: 13M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.apigee.edge.config:apigee-config-maven-plugin:1.2:keyvaluemaps (create-config-kvm) on project config-v1: null: MojoExecutionException -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Workaround is to place a file in the api directory so copy-resources and the replacer work.
$ tree edge
edge
├── api
│   └── README.md
└── org
 ......├── apiProducts.json
 ...... ├── developerApps.json
 ......└── developers.json

**Comment by kurtkanaskie** [comment]
There is a workaround to use an empty "api" directory and upgrade to maven-resources-plugin to 2.7
<plugin>
				<artifactId>maven-resources-plugin</artifactId>
				<version>2.7</version>
				<executions>
					<execution>
						<id>copy-resources</id>
						<phase>process-resources</phase>
						<goals>
							<goal>copy-resources</goal>
						</goals>
						<configuration>
							<includeEmptyDirs>true</includeEmptyDirs>

**Comment by msadasivam** [comment]
Fixed in v1.2.1
