### ISSUE TITLE
Not able to authenticate via SAML

### ISSUE THREAD

**Issue by iarellano** [apigee/apigee-config-maven-plugin#33]
I found that to authenticate via SAML, when bearer token is validated the plugin expects to be passed:
`-Dapigee.username=[token.email]`
But this is not documented anywhere. Line of code is: [Code line](https://github.com/apigee/apigee-config-maven-plugin/blob/ab35239c8a62d8ab007b00381da5f072c0974742/src/main/java/com/apigee/edge/config/rest/RestUtil.java#L1021).

**Comment by ssvaidyanathan** [comment]
yes.. thanks for the feedback.. let me update the docs..

can you confirm when you pass the username, it works as expected ?

**Comment by iarellano** [comment]
Yes it does.

Have my deployment working ever since, although imho I think we should provide the username at all since we are already providing the bearer token.

Thanks

**Comment by ssvaidyanathan** [comment]
thanks for getting back @iarellano 

yes - we did check and concluded that its a good additional check to have. Let me update the docs

**Comment by ssvaidyanathan** [comment]
done - please close if you think the details look good

**Comment by iarellano** [comment]
Sorry I did not mentioned also that beare parameter is expected to prefixed with apigee as:
`-Dapigee.bearer=`
and docs says:
`-Dbearer=`

Check at: [README.md](https://github.com/apigee/apigee-config-maven-plugin#passing-the-refresh-token-as-a-parameter)

Also after prefixing it, it worked too.

There is probably more places where this needs to addressed.

Happy to help.

**Comment by ssvaidyanathan** [comment]
well - it depends on how your pom profile is setup

[Here](https://github.com/apigee/apigee-config-maven-plugin/blob/master/samples/EdgeConfig/shared-pom.xml#L100), we use bearer, hence we have the same in the doc as well. Its just the system argument that is used at runtime

**Comment by iarellano** [comment]
Yup, I understan that, it is just the doc say:
`mvn install -Ptest -Dusername=$ae_username -Dauthtype=oauth -Dbearer=c912eu1201c -Dapigee.config.options=create`

When I think it should say:
`mvn install -Ptest -Dapigee.username=$ae_username -Dauthtype=oauth -Dapigee.bearer=c912eu1201c -Dapigee.config.options=create`

This issue came to me since I am automating the deployment for CI/CD so storing the token in the profile was not an option, that is how I got here.

I am going to close the issue and leave a reference to the code where properties are commented out: [GatewayAbstractMojo.java](https://github.com/apigee/apigee-config-maven-plugin/blob/master/src/main/java/com/apigee/edge/config/mavenplugin/GatewayAbstractMojo.java)

Thanks much Sai
