### ISSUE TITLE
How to handle caches [ ]  in edge.json?

### ISSUE THREAD

**Issue by Hambones** [apigee/apigee-config-maven-plugin#36]
Hi, I'm trying to figure out the best practice for handling caches as part of the lifecycle for an api proxy.
I included the cache definition in the edge.json file for each of my environments. Then in my maven build job, I included a goal to update the cache "apigee-config:caches".
This worked great the first time I deployed to each environment because it creates the cache, then deploys the proxy.
But now when I make any change to the proxy, the build job fails because it tries to delete & recreate the cache but it gets a message saying "Resource is in use".
I can understand not wanting to delete & create the cache every time we deploy a change, but I'm curious how people handle this issue.  

Do you change your build job to only include the "apigee-config:caches" goal the 1st time you deploy and then remove this goal?  Do you delete the cache details from edge.json after you've deployed it the first time?

It feels like the easiest way is to just manually create the cache in every environment and ignore the fact that I can include it in edge.json, so is there a better way?

**Comment by ssvaidyanathan** [comment]
HI @Hambones 

Can you please share the mvn command you are running ? What is the -Dapigee.config.options you are passing ?

**Comment by Hambones** [comment]
Sure. We've broken the build job up into 4 steps:
1) Goal:apigee-config:kvms apigee-config:caches apigee-config:targetservers
Options:  -Dapigee.config.options=sync
2) Goal: package
3) Goal: apigee-config:apiproducts
Options: -Dapigee.config.options=update
4) Goal: install
This has worked for other proxies, but we haven't had any others with caches defined.

**Comment by Hambones** [comment]
Ok - your question about the -Dapigee.config.options helped me realize there was a way to do it, I just had to split the build up some more.
I modified step (1) above to only "sync" the kvms and targetservers, then added a new step with goal: "apigee-config:caches" and option "-Dapigee.config.options=create" , and the build works now.
Thanks @ssvaidyanathan !

**Comment by ssvaidyanathan** [comment]
Cool.. Thanks. Please bear in mind that create is just one time process, when you run the job again with option as create, it would ignore it as its already there. If you run it as update, it will update the cache and if its not created, it would create as well. So please use update if you think thats more appropriate for your case.

I am closing this issue since you have it working
