### ISSUE TITLE
Export UI configurations to edge.json

### ISSUE THREAD

**Issue by ssvaidyanathan** [apigee/apigee-config-maven-plugin#4]
Would be nice to include a feature in the plugin that can export all the info like Product, Dev App, etc to edge.json

It is quite normal that many would use the UI to setup their products, dev app configurations. By using this feature, they can export that to edge.json and use that for other environments.

**Comment by pisitch1** [comment]
Mudit/I have a groovy scripts created for all that :)

**Comment by msadasivam** [comment]
https://github.com/apigeecs/apigee-migrate-tool would be the right place to do this. On the other hand we could support the more expanded config format of migrate tool. Let know.

If you have to write a script to support the plugins chances are it is a good feature request for any of the tools.

**Comment by ssvaidyanathan** [comment]
Agree this should be the task for the migrate tool
