### ISSUE TITLE
cache config didn't get populated by maven plugin

### ISSUE THREAD

**Issue by cameljava** [apigee/apigee-config-maven-plugin#44]
Hi, 
I am trying to run HelloWorld deployment using this maven plugin, noticed caches config is not picked up by com.apigee.edge.config:apigee-config-maven-plugin:1.2.1:targetservers, even though caches has already been defined in edge.json file.

**Comment by ssvaidyanathan** [comment]
@cameljava - you need to run the `caches` goal to configure Cache. The above command would only configure target server

**Comment by ssvaidyanathan** [comment]
@cameljava - can we close this issue ?

**Comment by ssvaidyanathan** [comment]
Closing this for now 
Please reopen if you continue to see the issue
