### ISSUE TITLE
Extension Policy support

### ISSUE THREAD

**Issue by Abdul-Kinadiyil** [apigee/apigee-config-maven-plugin#45]
Currently Maven plugin does not support installation and configuration of Apigee extension policies that enables connectivity to GCP and Informatica services. Customers have to manually invoke management APIs to install and configure extension policies.

**Comment by ssvaidyanathan** [comment]
Released in https://github.com/apigee/apigee-config-maven-plugin/releases/tag/apigee-config-maven-plugin-1.3.1
