### ISSUE TITLE
Delete option does not delete products, as used in Application

### ISSUE THREAD

**Issue by bhatikuldeep** [apigee/apigee-config-maven-plugin#46]
with options `-Dapigee.config.options=delete -Dapigee.config.dir=resources/edge` does not delete products, app; it returns 
```bash
[ERROR] Apigee call failed 400 Bad Request
{
  "code" : "mint.stillReferenced",
  "message" : "Cannot delete Product [weatherproduct] used in Application",
  "contexts" : [ ]
}
```

Ideally, it should delete but in reverse order first, app, developers and then products associated to each other, I guess that's not happening instead it first tries to delete products while apps/developers are associated to it hence it throws error.

**Comment by ssvaidyanathan** [comment]
The plugin doesnt do it automatically, it just considers the config thats passed. If you want a particular order, you can execute them by calling the maven goals, for example
`mvn apigee-config:apps apigee-config:apiproducts -Ptest -Dapigee.config.options=delete`

**Comment by bhatikuldeep** [comment]
thanks @ssvaidyanathan that's what I exactly did :)
I thought the plugin would consider that however running maven goal solves the problem!
```mvn apigee-config:apps apigee-config:developers apigee-config:apiproducts ..```
