### ISSUE TITLE
http.nonProxyHosts is getting overridden by default with blank

### ISSUE THREAD

**Issue by meghdeep-basu** [apigee/apigee-config-maven-plugin#5]
In plugin apigee-config-maven-plugin, system property http.nonProxyHosts is getting overridden by default with blank, which need to be fixed. We need this property to be functioning as expected according to java proxy standards here (https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html)]
# 

I have done some debugging, and can see the GatewayAbstractMojo.fixOSXNonProxyHosts() method is getting called from every Mojo execute method, fixOSXNonProxyHosts method is overriding always the system variable http.nonProxyHosts. If this method should behave as mentioned in the code comment, it should at least check the OS type to override this value.

protected void fixOSXNonProxyHosts() {

```
// This is required to work around a Mac OS X bug.  Probably would be better to be more selective about this.  Only override if we're
// actually on OS X.  Or look at the value and only unset if it contains the problematic wildcard value.
try {
       System.setProperty("http.nonProxyHosts", "");
}
catch (RuntimeException e) {
       // just try to continue
       getLog().error(e);
}
```

}

[INFO] --- apigee-config-maven-plugin:1.1-SNAPSHOT:caches (create-config-cache) @ Dummy ---
[INFO] ************************************************************************
[INFO] Apigee Cache
[INFO] ************************************************************************
[DEBUG] Build option update
[DEBUG] Base dir xxxx
[DEBUG] Retrieving config from edge.json
[INFO] Retrieving existing environment caches - xxx
[DEBUG] Request
GET xxxx
accept: application/json
accept-encoding: gzip
authorization: Basic [Not shown in log]
[ERROR] 503 Service Unavailable

Network Error

**Comment by meghdeep-basu** [comment]
I have done some debugging, and can see the GatewayAbstractMojo.fixOSXNonProxyHosts() method is getting called from every Mojo execute method, fixOSXNonProxyHosts method is overriding always the system variable http.nonProxyHosts. If this method should behave as mentioned in the code comment, it should at least check the OS type to override this value. 
 
-------------------------------------------------------------
protected void fixOSXNonProxyHosts() {
              
        // This is required to work around a Mac OS X bug.  Probably would be better to be more selective about this.  Only override if we're
        // actually on OS X.  Or look at the value and only unset if it contains the problematic wildcard value.
        try {
               System.setProperty("http.nonProxyHosts", "");
        }
        catch (RuntimeException e) {
               // just try to continue
               getLog().error(e);
        }
}
-------------------------------------------------------------
 
[INFO] --- apigee-config-maven-plugin:1.1-SNAPSHOT:caches (create-config-cache) @ Dummy ---
[INFO] ************************************************************************
[INFO] Apigee Cache
[INFO] ************************************************************************
[DEBUG] Build option update
[DEBUG] Base dir /var/SP/data/jenkins/workspace/apixdev-dev-deploy-1/Dummy
[DEBUG] Retrieving config from edge.json
[INFO] Retrieving existing environment caches - dev
[DEBUG] Request
GET  http://vgbx34vr.dc-dublin.de:8080/v1/organizations/apixdev/environments/dev/caches
accept: application/json
accept-encoding: gzip
authorization: Basic [Not shown in log]
[ERROR] 503 Service Unavailable
<HTML><HEAD>
<TITLE>Network Error</TITLE>
</HEAD>
<BODY>
<FONT face="Helvetica">

**Comment by msadasivam** [comment]
Proxy settings:

mvn install -Ptest -Denv=test -Dapigee.config.options=create \
           -Dhttp.nonProxyHosts='*.com|local*'
mvn install -Ptest -Denv=test -Dapigee.config.options=create \
           -Dhttps.proxyHost=192.168.21.97 -Dhttps.proxyPort=8081 \
           -Dhttp.nonProxyHosts='* .com|local*'
