### ISSUE TITLE
Using bearer token: Issue

### ISSUE THREAD

**Issue by AshwithGundu** [apigee/apigee-config-maven-plugin#54]
[ERROR] Failed to execute goal io.apigee.build-tools.enterprise4g:apigee-edge-maven-plugin:1.1.7:deploy (deploy-bundle) on project HelloWorld: MojoExecutionException: The token was expected to have 3 parts, but got 1. -> [Help 1]

**Comment by ssvaidyanathan** [comment]
looks like there was something wrong in the token you sent ? Is the Apigee org, SAML enabled ? Can you share the profile from your pom.xml that you are calling

**Comment by ssvaidyanathan** [comment]
hope this is resolved.. if yes, can you please close the issue ?

**Comment by ssvaidyanathan** [comment]
Closing this issue. Please reopen if its not working as expected
