### ISSUE TITLE
Using OAuth/SAML with a non-machine account

### ISSUE THREAD

**Issue by lllewellyn** [apigee/apigee-config-maven-plugin#56]
My team had this plugin working well with OAuth, using individual user accounts with the proper roles. Then we enabled SAML as well. Following the docs I adjusted the `apigee.tokenurl` to be

    ourZoneName.login.apigee.com/oauth/token

and ran Maven with the username/password for my account. Plugin failed with a 401. 

I then tried generating a passcode manually as described in [Apigee docs](https://docs.apigee.com/api-platform/system-administration/using-saml). I don't see a 'passcode' argument so provided it as the password hoping that would work. It didn't.

Reading the [source code](https://github.com/apigee/apigee-config-maven-plugin/blob/master/src/main/java/com/apigee/mgmtapi/sdk/client/MgmtAPIClient.java) it appears that the plugin only works with SAML for [machine users](https://docs.apigee.com/api-platform/system-administration/automating-tasks)? Thus if I want to use the plugin with SAML enabled and a personal account, I will have to generate the tokens outside the plugin and supply them as arguments?

If my understanding is correct, please consider making a note in the documentation about this. Also, I didn't see anything in the docs about specifying the `apigee.client` or `apigee.clientSecret` arguments which I think are required for machine accounts. Thanks!

**Comment by lllewellyn** [comment]
Thank you for adding the docs about `client` and `clientSecret`. I don't see anything about SAML however. The issue I encountered is related to enabling _both_ OAuth and SAML.

**Comment by ssvaidyanathan** [comment]
When you enable SAML, you just need to update the token url to include the auth endpoint. For example `https://zoneName.login.apigee.com/oauth/token`
Once you have the machine users setup, you should be able to use it like another org that is OAuth enabled. 
Please reopen this issue if you still have problems
