### ISSUE TITLE
build apiproduct fails if apiproxy is not deployed before

### ISSUE THREAD

**Issue by satish1240** [apigee/apigee-config-maven-plugin#57]
as per this config-plugin it first deploys the config in edge.json, which has apiproduct and proxies under neath. But those proxies will deployed with deploy-plugin after config-plugin finishes. But at the apiproduct deployment, build fails saying no apiproxy is found to add it to apiproduct as the proxy is not deployed.

How to overcome this or any solution?

**Comment by ssvaidyanathan** [comment]
@satish1240 - you should be able to control the logic within your pom.xml
Check [this sample](https://github.com/apigee/apigee-config-maven-plugin/blob/Issue-55/samples/APIandConfig/shared-pom.xml). It uses the maven phases to control that order. Try changing that in your pom and it should orchestrate based on Maven phases. Hope that helps

**Comment by satish1240** [comment]
@ssvaidyanathan Thanks for the explanation, in my pom deply-plugin is after config-plugin. making it reversed worked fine
