### ISSUE TITLE
Does config plugin supports Create/update reference

### ISSUE THREAD

**Issue by sunil001repo** [apigee/apigee-config-maven-plugin#59]
Does apigee-config-maven-plugin currently supports creating reference?or any plan to include in this plugin.

https://apidocs.apigee.com/management/apis/post/organizations/%7Borg_name%7D/environments/%7Benv_name%7D/references

**Comment by ssvaidyanathan** [comment]
not supported as of now. Can include it. Or else feel free to submit a PR with that enhancement :)

**Comment by ssvaidyanathan** [comment]
Available in v1.3.4

**Comment by sunil001repo** [comment]
Thanks.
