### ISSUE TITLE
Prevent 'secret' values from appearing in logs

### ISSUE THREAD

**Issue by Hambones** [apigee/apigee-config-maven-plugin#63]
When the apigee-config-maven-plugin updates KVMs, it displays the contents of the KVM in the log output.  We run maven as part of a release-pipeline in Azure Devops and quite a few people within the org have access to the logs, so this is seen as a security vulnerability.  Please provide a way to keep the content of the KVM confidential by not including it in the log output.

![2019-09-23 KVM-obfuscated](https://user-images.githubusercontent.com/26979478/65447558-6e16dd00-ddfc-11e9-9ac3-494fd94c3976.png)

**Comment by ssvaidyanathan** [comment]
@Hambones - would it be ok if I change that to debug in stead of info ? In that case, you will see the logs only when you run in debug mode with the `-X` command

**Comment by Hambones** [comment]
@ssvaidyanathan : Yes, I would be ok with it only being visible in debug, however I want to point out that the first time it appears is on the line above the first [INFO] ( line 9 in my screenshot ), so before you make a change I'd want to be sure you're addressing both occurrences of the text that I drew red boxes around.

**Comment by ssvaidyanathan** [comment]
thanks @Hambones. Point noted
Will provide an update once its pushed

**Comment by ssvaidyanathan** [comment]
v1.3.5 should have the fix
Please update your pom.xml pointing to this version
Please reopen the issue if the issue is not fixed

**Comment by Hambones** [comment]
Thank you! Issue is fixed with this update.
