### ISSUE TITLE
Support for KeyStores

### ISSUE THREAD

**Issue by guru12293** [apigee/apigee-config-maven-plugin#65]
Please enable the Keystores support for this plugin.

**Comment by karsten-wagner** [comment]
+1
It is a prerequisite to create a virtual host to have a key store with the certificate (& private key). So this is a feature I am missing to fully automate virtual host creation.

**Comment by lbajada** [comment]
+1 for this!

**Comment by afakhri** [comment]
+1
Keystore is a requierment for virtual hosts.

**Comment by indrajitp** [comment]
+1

I am also waiting for this feature.

**Comment by ssvaidyanathan** [comment]
v1.4.2 supports this
