### ISSUE TITLE
Release of 1.3.7 in online maven repo.

### ISSUE THREAD

**Issue by Abhishek-chouksey** [apigee/apigee-config-maven-plugin#68]
@ssvaidyanathan  on online repo the version 1.3.7 is not released it is still showing 1.3.6, can you please look into it.

**Comment by ssvaidyanathan** [comment]
@Abhishek-chouksey - I see it
https://search.maven.org/artifact/com.apigee.edge.config/apigee-config-maven-plugin/1.3.7/maven-plugin

Be sure your pom.xml is pointing to the correct version

```xml
<dependency>
  <groupId>com.apigee.edge.config</groupId>
  <artifactId>apigee-config-maven-plugin</artifactId>
  <version>1.3.7</version>
  <type>maven-plugin</type>
</dependency>
```
