### ISSUE TITLE
Enhancement for Data Masks

### ISSUE THREAD

**Issue by biresh-chatterjee** [apigee/apigee-config-maven-plugin#7]
It would be great if you can enhance the plugin to support Data Masks (http://docs.apigee.com/api-reference/content/data-masks) create/update.

**Comment by msadasivam** [comment]
Support for maskconfigs is now available. Please clone, build and give it a try. I will release it to maven repo after hearing your feedback.

**Comment by msadasivam** [comment]
This sample config includes maskconfigs for org and API scopes.
https://github.com/apigee/apigee-config-maven-plugin/blob/master/samples/EdgeConfig/edge.json

**Comment by msadasivam** [comment]
@biresh-chatterjee Did you get a chance to review maskconfigs and envProfileConfig enhancements.

**Comment by biresh-chatterjee** [comment]
@msadasivam Is it possible to break the latest change into two parts and tag
1. Only masking config enhancement
2. masking + env profile change
we want to first give a try to part 1 as it is simple, 2nd is hard to roll out as it needs adjustment to current configs.

**Comment by msadasivam** [comment]
@biresh-chatterjee they are both rolled into one commit. You can just validate the masking config changes.  It is unrelated to env profile changes and will work in the config format you already have. You can validate the env profile feature when you are ready.

**Comment by msadasivam** [comment]
Added support in e285244f690c29b760acae5690f1ff121e1789b8
Available in v1.1.3
