### ISSUE TITLE
We don't have deployment for apiproducts and developer 

### ISSUE THREAD

**Issue by maheshdhummi** [apigee/apigee-config-maven-plugin#71]
As per the above repo we don't have proper deployments for apiproducts and developerapps in env level this will be much required in banking applications

**Comment by ssvaidyanathan** [comment]
@maheshdhummi - In Apigee, the API Products and Developer Apps are org entities and not environment entities. That is why the samples have them under org

Hope that clarifies.

**Comment by maheshdhummi** [comment]
We know that's org entities, for standard RTL process apiproducts and developerapps needs to depolyed to each env, in those cases what action to be taken ??

**Comment by ssvaidyanathan** [comment]
@maheshdhummi - can you explain the ask in detail ? Not sure I understand.

**Comment by ssvaidyanathan** [comment]
Pls reopen if needed
