### ISSUE TITLE
Create api proxy from spec ?

### ISSUE THREAD

**Issue by luisdiezGL** [apigee/apigee-config-maven-plugin#75]
Hi, 
How create api proxy from openapi specification ?, using maven plugin.

Thanks !

**Comment by ssvaidyanathan** [comment]
@luisdiezGL - you can use [this npm](https://www.npmjs.com/package/openapi2apigee). And then call this within the pom. Usually its not done using a Maven pom. The usual process is

1. Create the spec
2. Generate the proxy using the spec in the UI
3. Download the code and commit to repo
4. Use the pom.xml to configure and deploy proxy using the Config and Deploy Maven plugins

There are no Maven plugins to generate the proxy from spec. So you could probably try calling the npm from the pom file using the exec-plugin. For example
```xml
<plugin>
	<groupId>org.codehaus.mojo</groupId>
	<artifactId>exec-maven-plugin</artifactId>
	<version>1.3.2</version>
	<executions>
		<!-- npm install -->
		<execution>
			<id>npm-install</id>
			<phase>validate</phase>
			<goals>
				<goal>exec</goal>
			</goals>
			<configuration>
				<executable>npm</executable>
				<commandlineArgs>
					install
				</commandlineArgs>
			</configuration>
		</execution>
		<!-- apigeelint -->
		<execution>
			<id>openapi2apigee</id>
			<phase>validate</phase>
			<goals>
				<goal>exec</goal>
			</goals>
			<configuration>
				<executable>node</executable>
				<commandlineArgs>
				    node_modules/openapi2apigee/lib/commands/generateApi/generateApi.js ${project.name} -s ${path-to-spec} -D -d .
				</commandlineArgs>
			</configuration>
		</execution>
	</executions>
</plugin>
```
NOTE: I have not tested this so please see if it works.

This plugin is meant for Apigee configurations. This plugin supports the Spec APIs where you can push the specs to Apigee. Will not be the place to generate the proxy 

Hope that clarifies

**Comment by luisdiezGL** [comment]
Hi @ssvaidyanathan ,
Thank you very much for the information.
I will try this option.

Regards

**Comment by ssvaidyanathan** [comment]
OK - Closing this issue. Please feel free to re-open just in case
