### ISSUE TITLE
[Hybrid] bearer token is missing

### ISSUE THREAD

**Issue by prabago** [apigee/apigee-config-maven-plugin#86]
Hello,

Recently version 2.0.1 has been released, version that supports authentication through user Bearer token.

I have updated the plugins to version 2.0.1, removed the path to the service account file and released the instruction:

mvn install -Ptest -Dbearer=$(gcloud auth print-access-token) -Dapigee.config.options=create

and I get the error:
[ERROR] Service Account file or bearer token is missing

![hybrid](https://user-images.githubusercontent.com/25517820/82227396-fb78e580-9927-11ea-941a-a7d09b84c6ee.png)

Same error when executed first obtain the my personal token with the command:
gcloud auth print-access-token

mvn install -Ptest -Dbearer=<<token>> -Dapigee.config.options=create
![hybrid2](https://user-images.githubusercontent.com/25517820/82230138-a048f200-992b-11ea-9f4a-043931d8cf55.png)

You know what I'm doing wrong?

Thank you very much in advance.

Best regards

**Comment by ssvaidyanathan** [comment]
HI @prabago 
Can you confirm you added the following property in your pom profile
`<apigee.bearer>$bearer</apigee.bearer>`
If not, please add that to your pom profile properties and try again

**Comment by prabago** [comment]
Hi  @ssvaidyanathan 

Effectively, my mistake was not adding the property <apigee.bearer>${bearer}</apigee.bearer> 

Once set, it works properly!

Thank you very much!

Best regards
