### ISSUE TITLE
Autoamted API proxy Flows creation using Open API specs

### ISSUE THREAD

**Issue by ayushj158** [apigee/apigee-config-maven-plugin#87]
Support to create API proxies flow from OpenAPI specs, At this moment it can be done only via UI, Could not find anything to acheive this in a autoamted way using CI/CD .

Current plugin, deploys specs and API proxy independetly but there association is not done

**Comment by ssvaidyanathan** [comment]
Hi @ayushj158 - check out [this issue](https://github.com/apigee/apigee-config-maven-plugin/issues/75)
