### ISSUE TITLE
Comment for the config entries

### ISSUE THREAD

**Issue by pisitch1** [apigee/apigee-config-maven-plugin#9]
We would like to have the ability for dev's to provide comments in the json file (through code-repo) so Ops knows what to set it in their environments (in config-repo)

See if something like "_comment" tag works...

{
  "_comment" : "this is the target server for PCF app backend"
  "host" : "sentry.test.ext.t-mobile.com",
  "isEnabled" : true,
  "name" : "NetworkEngineeringWSIL_POLARIS_Target",
  "port" : 8603,
  "sSLInfo" : {
    "ciphers" : [ ],
    "clientAuthEnabled" : "true",
    "enabled" : "true",
    "ignoreValidationErrors" : false,
    "keyAlias" : "dev01",
    "keyStore" : "dev01Keystore",
    "protocols" : [ ],
    "trustStore" : "dev01truststore"
  }
}

**Comment by msadasivam** [comment]
The config data will continue to work with any tool. I like this approach. 

Management APIs silently ignore additional attributes. I tried a call and this should work already  without any changes to the plugin.

Please give it a try and let know.

**Comment by ssvaidyanathan** [comment]
@pisitch1 
Yes - looks like _comment should work. I tried "description" which failed. So you can stick with _comment

Closing this issue. Please reopen if it fails for any config calls
